// create a runnable jar with jar dependencies stored in lib subdirectory
tasks.whenTaskAdded { task ->
    ['startScripts', 'distTar'].each { String skipTaskName ->
        if (task.name.contains(skipTaskName)) {
            task.enabled = false
        }
    }
}
apply plugin: 'java'
apply plugin: 'application'
// JDK 8
sourceCompatibility = 1.8
targetCompatibility = 1.8

String myAppName = 'PubmedCrawlerPipeline'
mainClassName = 'edu.mcw.rgd.nlp.utils.ncbi.PubMedLibrary'


repositories {
    mavenCentral()
    maven {
        url 'https://packages.atlassian.com/maven-3rdparty'
    }
}

dependencies {
    implementation fileTree(dir: 'lib', include: '*.jar')
    implementation 'log4j:log4j:1.2.17'
// https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.17.0'
// https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.17.0'

    // https://mvnrepository.com/artifact/org.jsonschema2pojo/jsonschema2pojo-core
    implementation group: 'org.jsonschema2pojo', name: 'jsonschema2pojo-core', version: '1.2.1'
    // https://mvnrepository.com/artifact/org.springframework/spring-jdbc
    implementation group: 'org.springframework', name: 'spring-jdbc', version: '5.3.39'
// https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2


}


jar {
    zip64=true
    archivesBaseName= myAppName
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'Built-By': System.getProperty('user.name'),
                'Built-Date': new Date(),
                'Built-JDK': System.getProperty('java.version'),
                'Class-Path': configurations.runtimeClasspath .collect { it.getName() }.join(' '),
                'Main-Class': mainClassName
        )
    }
    from {
        configurations.runtimeClasspath.collect{it.isDirectory()?it:zipTree(it)}
    }
}
distributions {
    main {
        distributionBaseName = myAppName
    }
}
task createDistro(type: Copy) {
    def zipFile = file('build/distributions/'+myAppName+'.zip')
    def outputDir = file("build/install")

    from zipTree(zipFile)
    into outputDir
}
createDistro.dependsOn assembleDist


task update_rgdcore(type:Copy){
    from file("../../rgd-core-library/dist/rgdcore_1.1.3.jar")
    into file("lib/")
}